accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView    # 追記
from django.contrib.auth.forms import UserCreationForm    # 追記


urlpatterns = [
    path('signup/', views.UserCreateAndLoginView.as_view(), name='signup'),  # 追記
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(),
        name='password_change_done'),
    path('user_delete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
]

loginTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
]

tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        _('username'),
        max_length=150,
    )
    email = models.EmailField(
        _('email address'),
        unique=True,
    )
    age = models.PositiveIntegerField(('年齢'), default=0, blank=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    data_joined = models.DateTimeField(_('data joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'
        swappable = 'AUTH_USER_MODEL'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'age')
         
class UserUpdateForm(forms.ModelForm):
        class Meta:
            model = CustomUser
            fields = (
            'username',
            'email',
            'age',
        )

tasks/forms.py
from django import forms


class TaskCreationForm(forms.Form):
    title = forms.CharField(label='タイトル', max_length=255)
    content = forms.CharField(label='内容', widget=forms.Textarea())

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from .forms import CustomUserCreationForm 

from django.contrib.auth import get_user_model
from django.views.generic import DetailView

from .forms import (
    CustomUserCreationForm,
    UserUpdateForm,
)    # 変更
from django.contrib.auth import get_user_model
from django.views.generic import (
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse

from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView
) 
from django.contrib.auth.mixins import UserPassesTestMixin

User = get_user_model()
class OnlyYouMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser
    
class UserCreateAndLoginView(CreateView):
    form_class = CustomUserCreationForm 
    template_name = "signup.html"
    success_url = reverse_lazy("tasks:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data.get("email")
        raw_pw = form.cleaned_data.get("password1")
        user = authenticate(email=email, password=raw_pw)
        login(self.request, user)
        return response

class UserDetail(OnlyYouMixin, DetailView):
    model = User
    template_name = 'user_detail.html'
class UserUpdate(OnlyYouMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'user_edit.html'

    def get_success_url(self):
        return reverse('user_detail', kwargs={'pk': self.kwargs['pk']})

class PasswordChange(PasswordChangeView):
    template_name = 'password_change.html'
class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'user_detail.html'
class UserDelete(OnlyYouMixin, DeleteView):
    model = User
    template_name = 'user_delete.html'
    success_url = reverse_lazy('login')

tasks/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Task
from .forms import TaskCreationForm
from django.contrib.auth.decorators import login_required


def index(request):
    tasks = Task.objects.all()
    params = {
        'tasks': tasks,
    }
    return render(request, 'tasks/index.html', params)

@login_required 
def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('tasks:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)


def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    params = {
        'task': task,
    }
    return render(request, 'tasks/detail.html', params)


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.title = request.POST['title']
        task.content = request.POST['content']
        task.save()
        return redirect('tasks:detail', task_id)
    else:
        form = TaskCreationForm(initial={
            'title': task.title,
            'content': task.content,
        })
        params = {
            'task': task,
            'form': form,
        }
        return render(request, 'tasks/edit.html', params)


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.delete()
        return redirect('tasks:index')
    else:
        params = {
            'task': task,
        }
        return render(request, 'tasks/delete.html', params)

accounts/templates/login.html
{% extends "base.html" %}

{% block main %}
<h1>Login</h1>

<form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />
  {{ form.as_p }}
  <input type="submit" value="ログイン">
</form>
{% endblock %}

accounts/templates/password_change.html
{% extends "base.html" %}

{% block main %}
<h1>Cambiar contraseña</h1>
<form action="" method="POST">
{{ form.as_p }}
{% csrf_token %}
<button type="submit">変更する</button>
</form>
<a href="{% url 'user_detail' user.id %}">戻る</a>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}

{% block main %}
<h2>Registro</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="登録">
</form>
{% endblock %}

accounts/templates/user_delete.html
{% extends "base.html" %}

{% block main %}
<h1>Eliminar usuario</h1>
<table>
<tbody>
<tr>
    <th>ユーザー名</th>
    <td>{{ user.username }}</td>
    </tr>
    <tr>
    <th>メールアドレス</th>
    <td>{{ user.email }}</td>
    </tr>
    <tr>
    <th>年齢</th>
    <td>{{ user.age }}</td>
    </tr>
</tbody>
</table>

<form action="{% url 'user_delete' user.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="退会する">
</form>

<a href="{% url 'user_detail' user.id %}">戻る</a>
{% endblock %}

accounts/templates/user_detail.html
{% extends "base.html" %}

{% block main %}
<h1>Detalles del usuario</h1>
<table>
    <tbody>
    <tr>
        <th>Usuario</th>
        <td>{{ user.username }}</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>{{ user.email }}</td>
    </tr>
    <tr>
        <th>Edad</th>
        <td>{{ user.age }}</td>
    </tr>
    </tbody>
</table>
<a href="{% url 'user_update' user.pk %}">Actualizar datos</a>
<a href="{% url 'password_change' %}">Cambiar contraseña</a>    <!-- 追記 -->
{% endblock %}

accounts/templates/user_edit.html
{% extends "base.html" %}

{% block main %}
<h1>Editar usuario</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="更新する">
</form>
<a href="{% url 'user_detail' user.id %}">Atras</a>
<a href="{% url 'user_delete' user.id %}">Eliminar</a>
{% endblock %}

tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block main %}
<h1>タスク登録ページ</h1>
<form action="{% url 'tasks:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="登録する">
</form>

<br>

<a href="{% url 'tasks:index' %}">戻る</a>
{% endblock %}

tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% block main %}
<h1>タスク削除ページ</h1>
<p>
  <strong>タイトル:</strong>
  {{task.title}}
</p>

<p>
  <strong>内容:</strong>
  {{task.content}}
</p>
<form action="{% url 'tasks:delete' task.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="削除">
</form>

<br>

<a href="{% url 'tasks:index' %}">戻る</a>
{% endblock %}

tasks/templates/tasks/detail.html
{% extends "base.html" %}

{% block main %}
<h1>タスク詳細ページ</h1>
<p>
  <strong>タイトル:</strong>
  {{task.title}}
</p>

<p>
  <strong>内容:</strong>
  {{task.content}}
</p>
<a href="{% url 'tasks:index' %}">戻る</a> |
<a href="{% url 'tasks:edit' task.id %}">編集</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block main %}
<h1>タスク編集ページ</h1>
<form action="{% url 'tasks:edit' task.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="更新する">
</form>

<br>

<a href="{% url 'tasks:detail' task.id %}">詳細</a> |
<a href="{% url 'tasks:index' %}">戻る</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block main %}
<h1>タスク一覧ページ</h1>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th colspan="3"></th>
  </tr>
  {% for task in tasks %}
  <tr>
    <td>{{task.title}}</td>
    <td>{{task.content}}</td>
    <td><a href="{% url 'tasks:detail' task.id %}">詳細</a></td>
    <td><a href="{% url 'tasks:edit' task.id %}">編集</a></td>
    <td><a href="{% url 'tasks:delete' task.id %}">削除</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'tasks:create' %}">新規作成</a>

{% endblock %}

templates/base.html
{% load static %}

<html>

  <head>
    <meta charset="utf-8">
    <title>Task</title>
    <link rel="stylesheet" href="{% static 'tasks/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}">
  </head>

  <body>
    <nav>
      <ul>
        <!-- ここから -->
        {% if user.is_authenticated %}
        <li><a href="{% url 'tasks:index' %}">Lista blog</a></li>
        <li><a href="{% url 'user_detail' user.pk %}">Información de miembro</a></li>    <!-- 追記 -->
        <li><form id="logoutForm" method="post" action="{% url 'logout' %}" style="display: inline;">
          {% csrf_token %}
          <button type="submit" style="background: none; border: none; padding: 0; font: inherit; cursor: pointer; color: white; margin-top: 13px;">Cerrar sesión</button>
      </form></li>
        {% else %}
        <li><a href="{% url 'login' %}">Iniciar sesion</a></li>
        <li><a href="{% url 'signup' %}">Registro</a></li>
        {% endif %}
        <!-- ここまで -->
      </ul>
    </nav>
    <main>
      <div>
        {% block main %}
        {% endblock %}
      </div>
    </main>
  </body>

</html>